steps:
  - name: node:18
    entrypoint: yarn
    args: ["install"]
    dir: "./"

  - name: node:18
    entrypoint: yarn
    args: ["run", "build"]
    dir: "./"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "functions",
        "deploy",
        "pixiv-to-raindrop",
        "--entry-point=synchronize",
        "--runtime=nodejs16",
        "--trigger-http",
        "--source=./dist",
        "--allow-unauthenticated",
      ]
    dir: "./"
